puts "The students of my cohort at Makers Academy"
puts "-----------------"
puts "Dr. Hannible Lecter"
puts "Darth Vadar"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex De Large"
puts "The Alien"
puts "Terminator"
puts "Freddy Kruger"
puts "The Joker"